version: '3.8'

services:
  db:
    image: postgres:17.0
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - db-network

  static:
    build:
      context: .
      dockerfile: services/static/Dockerfile.dev
    volumes:
      - ./static:/app/static
    ports:
      - "5173:5173"
    restart: always

  web:
    build:
      context: .
      dockerfile: services/web/Dockerfile.dev
    environment:
      - DEBUG=true
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    restart: always
    command: >
      sh -c "wait-for-it db:5432 -- &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py makesuperuser &&
      python manage.py runserver 0.0.0.0:4000"
    depends_on:
      - db
      - static
    networks:
      - db-network

volumes:
  caddy_data:
  caddy_config:
  pgdata:
  media:
  files:

networks:
  db-network:
    driver: bridge
