name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ./mariafm

            make down-prod
            git restore .
            git pull

            # server
            echo "SECRET= ${{ secrets.SECRET }}" > .env
            
            echo "POSTGRES_DB= ${{ secrets.POSTGRES_DB }}" >> .env
            echo "POSTGRES_USER= ${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD= ${{ secrets.POSTGRES_PASSWORD }}" >> .env
            
            echo "SUPERUSER_EMAIL= ${{ secrets.SUPERUSER_EMAIL }}" >> .env
            echo "SUPERUSER_USERNAME= ${{ secrets.SUPERUSER_USERNAME }}" >> .env
            echo "SUPERUSER_PASSWORD= ${{ secrets.SUPERUSER_PASSWORD }}" >> .env
            
            echo "HOST= ${{ secrets.HOST }}" >> .env

            make build-prod
            make up-prod